# Generated by Django 4.0 on 2022-01-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='student_class',
            field=models.CharField(max_length=50),
        ),
    ]
